import { StyleSheet } from "react-native";

const bayangan = {
  shadowColor: "#000",
  shadowOffset: { width: 0, height: 2 },
  shadowOpacity: 0.08,
  shadowRadius: 6,
  elevation: 3,
};

export const styles = StyleSheet.create({
  container: { flex: 1, alignItems: "center", justifyContent: "center", padding: 24, backgroundColor: "#F5F6FA" },
  containerRak: { flex: 1, backgroundColor: "#F5F6FA" },
  containerRakGelap: { backgroundColor: "#121212" },
  containerBaca: { flex: 1, backgroundColor: "#fff" },
  containerGelap: { backgroundColor: "#161616" },

  headerRak: {
    paddingHorizontal: 20, paddingTop: 20, paddingBottom: 16, backgroundColor: "#fff",
    borderBottomLeftRadius: 24, borderBottomRightRadius: 24, ...bayangan,
  },
  headerRakGelap: { backgroundColor: "#1E1E1E", shadowOpacity: 0 },
  barisJudulRak: { flexDirection: "row", justifyContent: "space-between", alignItems: "flex-start", marginBottom: 16 },
  judul: { fontSize: 28, fontWeight: "800", color: "#1F2937", letterSpacing: -0.5 },
  teksGelapUtama: { color: "#F3F4F6" },
  subjudulRak: { fontSize: 13, color: "#9CA3AF", marginTop: 2 },
  saklarRak: { backgroundColor: "#F0F3F9", borderRadius: 14, paddingHorizontal: 12, paddingVertical: 8, marginTop: 4 },
  saklarRakAktif: { backgroundColor: "#2A2A2A" },
  teksSaklarRak: { fontSize: 12, fontWeight: "700", color: "#4A6FA5" },
  tombolTambah: {
    backgroundColor: "#4A6FA5", paddingVertical: 12, paddingHorizontal: 18, borderRadius: 14,
    alignItems: "center", ...bayangan,
  },
  teksTombolTambah: { color: "#fff", fontWeight: "700", fontSize: 14 },

  subjudul: { fontSize: 14, color: "#7F8C8D", marginBottom: 32 },
  tombolUtama: { backgroundColor: "#4A6FA5", paddingVertical: 14, paddingHorizontal: 32, borderRadius: 14, ...bayangan },
  teksTombolUtama: { color: "#fff", fontSize: 16, fontWeight: "700" },
  teksLoading: { marginTop: 12, color: "#7F8C8D" },

  daftarRiwayat: { paddingHorizontal: 16, paddingTop: 18, paddingBottom: 24 },
  gridBaris: { justifyContent: "space-between", marginBottom: 16 },

  itemRiwayat: { width: "48%", backgroundColor: "#fff", borderRadius: 16, overflow: "hidden", ...bayangan },
  itemRiwayatGelap: { backgroundColor: "#1E1E1E" },
  ikonBuku: { width: "100%", height: 130, alignItems: "center", justifyContent: "center" },
  teksIkonBuku: { color: "#fff", fontSize: 22, fontWeight: "800", letterSpacing: 1 },
  infoRiwayat: { padding: 12 },
  namaRiwayat: { fontSize: 13.5, fontWeight: "700", color: "#1F2937", lineHeight: 18 },
  subRiwayat: { fontSize: 11.5, color: "#9CA3AF", marginTop: 4 },
  tombolHapus: {
    position: "absolute", top: 6, right: 6, width: 24, height: 24, borderRadius: 12,
    backgroundColor: "rgba(0,0,0,0.35)", alignItems: "center", justifyContent: "center",
  },
  teksHapus: { color: "#fff", fontSize: 13, fontWeight: "700" },

  header: {
    flexDirection: "row", alignItems: "center", paddingHorizontal: 14, paddingVertical: 12,
    borderBottomWidth: 1, borderBottomColor: "#EEF0F3", backgroundColor: "#fff",
    ...bayangan, shadowOpacity: 0.04, elevation: 2,
  },
  tombolKembali: { marginRight: 12 },
  tombolHeaderKanan: { marginLeft: 18 },
  teksKembali: { color: "#4A6FA5", fontSize: 15, fontWeight: "700" },
  namaFileHeader: { flex: 1, fontSize: 14.5, fontWeight: "600", color: "#1F2937" },
  pdf: { flex: 1, width: "100%", height: "100%" },

  navigasi: {
    flexDirection: "row", justifyContent: "space-between", alignItems: "center",
    paddingHorizontal: 10, paddingVertical: 6, borderTopWidth: 1, borderTopColor: "#E5E5E5",
  },
  teksNavigasi: { color: "#2C3E50" },

  navigasiBaru: {
    flexDirection: "row", alignItems: "center", justifyContent: "space-between",
    paddingHorizontal: 14, paddingVertical: 10, borderTopWidth: 1, borderTopColor: "#EEF0F3", backgroundColor: "#fff",
  },
  tombolNav: { width: 38, height: 38, borderRadius: 19, backgroundColor: "#F0F3F9", alignItems: "center", justifyContent: "center" },
  teksTombolNav: { fontSize: 16, fontWeight: "800", color: "#4A6FA5" },
  tombolNavKecil: { width: 30, height: 30, borderRadius: 15, alignItems: "center", justifyContent: "center" },
  teksTombolNavKecil: { fontSize: 12, fontWeight: "800", color: "#8CA3C7" },
  teksNavNonaktif: { color: "#D5D9E0" },
  indikatorHalamanTombol: { backgroundColor: "#F0F3F9", borderRadius: 20, paddingHorizontal: 16, paddingVertical: 8 },
  teksIndikatorHalamanTombol: { fontSize: 13, fontWeight: "700", color: "#2C3E50" },

  kotakLompatHalaman: { backgroundColor: "#fff", borderRadius: 18, padding: 22, marginHorizontal: 32, ...bayangan, shadowOpacity: 0.2 },
  labelLompatHalaman: { fontSize: 13, color: "#7F8C8D", marginBottom: 14 },
  inputLompatHalaman: {
    borderWidth: 1.5, borderColor: "#E1E5EB", borderRadius: 12, paddingHorizontal: 14,
    paddingVertical: 10, fontSize: 16, marginBottom: 18, textAlign: "center",
  },
  barisTombolLompat: { flexDirection: "row", gap: 10 },
  tombolBatalLompat: { flex: 1, paddingVertical: 12, borderRadius: 12, backgroundColor: "#F0F3F9", alignItems: "center" },
  teksTombolBatalLompat: { color: "#7F8C8D", fontWeight: "700" },
  tombolKirimLompat: { flex: 1, paddingVertical: 12, borderRadius: 12, backgroundColor: "#4A6FA5", alignItems: "center" },
  teksTombolKirimLompat: { color: "#fff", fontWeight: "700" },

  indikatorLatar: { flexDirection: "row", alignItems: "center", justifyContent: "center", paddingVertical: 7, backgroundColor: "#F0F3F9" },
  teksIndikatorLatar: { fontSize: 11, color: "#7F8C8D", marginLeft: 8 },

  overlay: { flex: 1, backgroundColor: "rgba(15,20,30,0.5)", justifyContent: "flex-end", alignItems: "center" },
  panelPengaturan: { backgroundColor: "#fff", borderTopLeftRadius: 22, borderTopRightRadius: 22, padding: 24, maxHeight: "80%", width: "100%" },
  judulPanel: { fontSize: 18, fontWeight: "800", color: "#1F2937", marginBottom: 20 },
  labelPanel: { fontSize: 14, fontWeight: "600", color: "#4B5563", marginBottom: 10 },
  barisFont: { flexDirection: "row", alignItems: "center", marginBottom: 24 },
  tombolFont: { backgroundColor: "#F0F3F9", paddingVertical: 10, paddingHorizontal: 18, borderRadius: 10 },
  teksTombolFont: { fontSize: 16, fontWeight: "700", color: "#4A6FA5" },
  angkaFont: { marginHorizontal: 20, fontSize: 16, fontWeight: "700", color: "#1F2937", minWidth: 30, textAlign: "center" },
  barisModeGelap: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginBottom: 20 },
  saklar: { width: 50, height: 28, borderRadius: 14, backgroundColor: "#D8DCE3", padding: 3 },
  saklarAktif: { backgroundColor: "#4A6FA5" },
  bulatSaklar: { width: 22, height: 22, borderRadius: 11, backgroundColor: "#fff" },
  bulatSaklarAktif: { marginLeft: 22 },
  blokBahasa: { marginTop: 12, marginBottom: 8 },
  barisChip: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
  chipBahasa: { borderWidth: 1.5, borderColor: "#E1E5EB", borderRadius: 20, paddingVertical: 8, paddingHorizontal: 16 },
  chipBahasaAktif: { backgroundColor: "#4A6FA5", borderColor: "#4A6FA5" },
  teksChip: { color: "#4B5563", fontSize: 13, fontWeight: "600" },
  teksChipAktif: { color: "#fff", fontWeight: "700" },
  catatanMetode: { fontSize: 12, color: "#B0730E", marginTop: 8, lineHeight: 17 },

  barisCari: { flexDirection: "row", alignItems: "center", padding: 14, gap: 10, borderBottomWidth: 1, borderBottomColor: "#EEF0F3" },
  inputCari: { flex: 1, borderWidth: 1.5, borderColor: "#E1E5EB", borderRadius: 12, paddingHorizontal: 14, paddingVertical: 10, fontSize: 15 },
  tombolCariAksi: { backgroundColor: "#4A6FA5", paddingVertical: 11, paddingHorizontal: 18, borderRadius: 12 },
  teksTombolCariAksi: { color: "#fff", fontWeight: "700" },
  daftarHasilCari: { padding: 14 },
  itemHasilCari: { backgroundColor: "#F5F6FA", borderRadius: 12, padding: 14, marginBottom: 10 },
  labelBabHasil: { fontSize: 12, fontWeight: "800", color: "#4A6FA5", marginBottom: 4 },
  cuplikanHasil: { fontSize: 14, color: "#374151", lineHeight: 20 },
  teksKosongCari: { textAlign: "center", color: "#9CA3AF", marginTop: 40 },
});