import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: { flex: 1, alignItems: "center", justifyContent: "center", padding: 24, backgroundColor: "#F7F8FA" },
  containerRak: { flex: 1, backgroundColor: "#F7F8FA" },
  containerBaca: { flex: 1, backgroundColor: "#fff" },
  containerGelap: { backgroundColor: "#1A1A1A" },
  headerRak: {
    flexDirection: "row", justifyContent: "space-between", alignItems: "center",
    paddingHorizontal: 20, paddingVertical: 16,
  },
  judul: { fontSize: 26, fontWeight: "bold", color: "#2C3E50" },
  tombolTambah: { backgroundColor: "#4A6FA5", paddingVertical: 8, paddingHorizontal: 14, borderRadius: 8 },
  teksTombolTambah: { color: "#fff", fontWeight: "600", fontSize: 13 },
  subjudul: { fontSize: 14, color: "#7F8C8D", marginBottom: 32 },
  tombolUtama: { backgroundColor: "#4A6FA5", paddingVertical: 14, paddingHorizontal: 32, borderRadius: 10 },
  teksTombolUtama: { color: "#fff", fontSize: 16, fontWeight: "600" },
  teksLoading: { marginTop: 12, color: "#7F8C8D" },
  daftarRiwayat: { paddingHorizontal: 16, paddingBottom: 16 },
  itemRiwayat: {
    flexDirection: "row", alignItems: "center", backgroundColor: "#fff",
    borderRadius: 12, padding: 12, marginBottom: 10,
  },
  ikonBuku: {
    width: 44, height: 44, borderRadius: 8, backgroundColor: "#4A6FA5",
    alignItems: "center", justifyContent: "center", marginRight: 12,
  },
  teksIkonBuku: { color: "#fff", fontSize: 10, fontWeight: "bold" },
  infoRiwayat: { flex: 1 },
  namaRiwayat: { fontSize: 15, fontWeight: "600", color: "#2C3E50" },
  subRiwayat: { fontSize: 12, color: "#7F8C8D", marginTop: 2 },
  tombolHapus: { padding: 8 },
  teksHapus: { color: "#B0B0B0", fontSize: 16 },
  header: {
    flexDirection: "row", alignItems: "center", paddingHorizontal: 12, paddingVertical: 10,
    borderBottomWidth: 1, borderBottomColor: "#E5E5E5", backgroundColor: "#fff",
  },
  tombolKembali: { marginRight: 12 },
  tombolHeaderKanan: { marginLeft: 16 },
  teksKembali: { color: "#4A6FA5", fontSize: 16, fontWeight: "600" },
  namaFileHeader: { flex: 1, fontSize: 15, fontWeight: "500", color: "#2C3E50" },
  pdf: { flex: 1, width: "100%", height: "100%" },
  navigasi: {
    flexDirection: "row", justifyContent: "space-between", alignItems: "center",
    paddingHorizontal: 10, paddingVertical: 6, borderTopWidth: 1, borderTopColor: "#E5E5E5",
  },
  teksNavigasi: { color: "#2C3E50" },
  indikatorLatar: {
    flexDirection: "row", alignItems: "center", justifyContent: "center",
    paddingVertical: 6, backgroundColor: "#F0F2F5",
  },
  teksIndikatorLatar: { fontSize: 11, color: "#7F8C8D", marginLeft: 8 },
  overlay: { flex: 1, backgroundColor: "rgba(0,0,0,0.4)", justifyContent: "flex-end" },
  panelPengaturan: { backgroundColor: "#fff", borderTopLeftRadius: 16, borderTopRightRadius: 16, padding: 24, maxHeight: "80%" },
  judulPanel: { fontSize: 18, fontWeight: "bold", color: "#2C3E50", marginBottom: 20 },
  labelPanel: { fontSize: 15, color: "#2C3E50", marginBottom: 10 },
  barisFont: { flexDirection: "row", alignItems: "center", marginBottom: 24 },
  tombolFont: { backgroundColor: "#F0F2F5", paddingVertical: 10, paddingHorizontal: 18, borderRadius: 8 },
  teksTombolFont: { fontSize: 16, fontWeight: "600", color: "#4A6FA5" },
  angkaFont: { marginHorizontal: 20, fontSize: 16, fontWeight: "600", color: "#2C3E50", minWidth: 30, textAlign: "center" },
  barisModeGelap: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginBottom: 20 },
  saklar: { width: 50, height: 28, borderRadius: 14, backgroundColor: "#D0D0D0", padding: 3 },
  saklarAktif: { backgroundColor: "#4A6FA5" },
  bulatSaklar: { width: 22, height: 22, borderRadius: 11, backgroundColor: "#fff" },
  bulatSaklarAktif: { marginLeft: 22 },
  blokBahasa: { marginTop: 12, marginBottom: 8 },
  barisChip: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
  chipBahasa: {
    borderWidth: 1, borderColor: "#D0D0D0", borderRadius: 20,
    paddingVertical: 8, paddingHorizontal: 16,
  },
  chipBahasaAktif: { backgroundColor: "#4A6FA5", borderColor: "#4A6FA5" },
  teksChip: { color: "#2C3E50", fontSize: 13 },
  teksChipAktif: { color: "#fff", fontWeight: "600" },
  catatanMetode: { fontSize: 12, color: "#B0730E", marginTop: 8, lineHeight: 17 },
  barisCari: {
    flexDirection: "row", alignItems: "center", padding: 12, gap: 8,
    borderBottomWidth: 1, borderBottomColor: "#E5E5E5",
  },
  inputCari: {
    flex: 1, borderWidth: 1, borderColor: "#D0D0D0", borderRadius: 8,
    paddingHorizontal: 12, paddingVertical: 8, fontSize: 15,
  },
  tombolCariAksi: { backgroundColor: "#4A6FA5", paddingVertical: 10, paddingHorizontal: 16, borderRadius: 8 },
  teksTombolCariAksi: { color: "#fff", fontWeight: "600" },
  daftarHasilCari: { padding: 12 },
  itemHasilCari: {
    backgroundColor: "#F7F8FA", borderRadius: 10, padding: 12, marginBottom: 8,
  },
  labelBabHasil: { fontSize: 12, fontWeight: "700", color: "#4A6FA5", marginBottom: 4 },
  cuplikanHasil: { fontSize: 14, color: "#2C3E50", lineHeight: 20 },
  teksKosongCari: { textAlign: "center", color: "#7F8C8D", marginTop: 40 },
  panelTerjemahanPdfBawah: {
    flex: 0.45,
    borderTopWidth: 1,
    borderTopColor: "#E5E5E5",
    backgroundColor: "#F7F8FA",
  },
  headerTerjemahanPdfKecil: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: "#E5E5E5",
    backgroundColor: "#fff",
  },
  labelTerjemahanPdfKecil: {
    fontSize: 13,
    fontWeight: "600",
    color: "#2C3E50",
  },
  webviewTerjemahanPdf: {
    flex: 1,
  },
});